[versions]
androidGradlePlugin = "8.3.2"
appcompat = "1.7.0"
kotlin = "1.9.22"
kotlinxCoroutinesAndroid = "1.7.3"
library = "1.0.0"
libraryVersion = "2.0.0"
sdk = "35"
androidxCore = "1.16.0"
androidxAppcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
fragment = "1.8.7"
activity = "1.10.1"
lifecycle = "2.9.0"
retrofit = "2.11.0"
gsonConverter = "2.11.0"
glide = "4.16.0"
hilt = "2.51"
junit = "4.13.2"
junitExt = "1.2.1"
espressoCore = "3.6.1"
coroutines = "1.7.1"
activityCompose = "1.10.1"
composeBom = "2024.02.01"
transitiveLib = "1.5.0"

[libraries]
androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
anotherLibrary = { module = "another:library", version.ref = "libraryVersion" }
appcompatV161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
library = { module = "some:library", version.ref = "library" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidxFragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidxActivityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidxLifecycleViewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxLifecycleLivedataKtx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gsonConverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gsonConverter" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxUi = { group = "androidx.compose.ui", name = "ui", version.ref = "composeBom" }
androidxUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeBom" }
androidxUiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeBom" }
androidxUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeBom" }
androidxUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeBom" }
androidxUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeBom" }
androidxMaterial3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeBom" }

hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
transitiveLib = { module = "com.example.transitive:transitive-lib", version.ref = "transitiveLib" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
