[versions]
agp = "8.11.1"
autoimageslider = "1.4.0"
firebaseBomVersion = "33.16.0"
firebaseuiFirebaseUiFirestore = "8.0.2"
firebaseUiFirestoreVersion = "9.0.0"
kotlin = "2.2.0"

# Firebase
firebaseBom = "33.16.0"
firebaseUiFirestore = "9.0.0"
firebaseAuthKtx = "23.2.1"
firebaseFirestoreKtx = "25.1.4"
firebaseStorageKtx = "21.0.2"

# AndroidX Core
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
paging = "3.2.0"

# UI / Animation / Image / Persistence
lottie = "6.6.7"
lottieLegacy = "5.2.0"
pagingRuntimeKtx = "3.2.1"
pagingRuntimeKtxVersion = "3.3.6"
picasso = "2.71828"
paperdb = "2.7.2"

# Testing
junit = "4.13.2"
junitExt = "1.2.1"
espressoCore = "3.6.1"
viewpager2 = "1.1.0"
roomCommonJvm = "2.7.2"
roomRuntimeAndroid = "2.7.2"
lifecycleViewmodelAndroid = "2.9.2"
playServicesAnalyticsImpl = "18.2.0"



[libraries]

# 🧩 AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-paging-runtime-ktx-v321 = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-paging-runtime-ktx-v336 = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtxVersion" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
autoimageslider = { module = "com.github.smarteist:autoimageslider", version.ref = "autoimageslider" }
firebase-bom-v3310 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-ui-firestore-v802 = { module = "com.firebaseui:firebase-ui-firestore", version.ref = "firebaseUiFirestoreVersion" }
firebaseui-firebase-ui-firestore-v802 = { module = "com.firebaseui:firebase-ui-firestore", version.ref = "firebaseuiFirebaseUiFirestore" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
google-firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

# 🎯 Material & UI Components
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-legacy = { module = "com.airbnb.android:lottie", version.ref = "lottieLegacy" }

# 🔥 Firebase (using BoM)
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
firebase-ui-firestore = { module = "com.firebaseui:firebase-ui-firestore", version.ref = "firebaseUiFirestore" }

# 💾 Persistence & Images
paperdb = { module = "io.github.pilgr:paperdb", version.ref = "paperdb" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

# 🧪 Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime-android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
androidx-lifecycle-viewmodel-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycleViewmodelAndroid" }
play-services-analytics-impl = { group = "com.google.android.gms", name = "play-services-analytics-impl", version.ref = "playServicesAnalyticsImpl" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.3" }
