[versions]
androidGradlePlugin = "8.10.1"      # OK, última estable
kotlin = "1.9.22"                   # OK, última estable
kotlinxCoroutinesAndroid = "1.7.3" # OK
library = "1.0.0"                   # Asumo interna, OK
libraryVersion = "2.0.0"            # Asumo interna, OK
sdk = "35"                         # API 35 OK
androidxCore = "1.16.0"             # OK
androidxAppcompat = "1.7.0"         # OK
material = "1.12.0"                 # OK, Material Components for Android
constraintlayout = "2.2.1"          # OK
recyclerview = "1.4.0"              # OK
fragment = "1.8.7"                  # OK
activity = "1.10.1"                 # OK
lifecycle = "2.9.0"                 # OK
retrofit = "2.11.0"                 # OK
gsonConverter = "2.11.0"            # OK
glide = "4.16.0"                    # OK
hilt = "2.51"                      # OK
junit = "4.13.2"                   # OK
junitExt = "1.2.1"                  # OK
espressoCore = "3.6.1"              # OK
coroutines = "1.7.1"                # OK
activityCompose = "1.10.1"          # OK

# Aquí vienen las correcciones importantes para Compose:
# composeBom: NO existe la versión 2025.06.01, usa versión estable actual:
composeBom = "2023.09.01"            # versión BOM estable
composeCompiler = "1.6.7"             # OK última estable compatible con Compose 1.6.x

firebaseBom = "32.7.0"                # OK
room = "2.6.1"                       # OK
transitiveLib = "1.5.0"              # Supongo interna o local, OK si es válida

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

androidxFragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidxActivityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidxLifecycleViewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxLifecycleLivedataKtx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidxLifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gsonConverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gsonConverter" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidxUi = { group = "androidx.compose.ui", name = "ui", version.ref = "composeBom" }
androidxUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeBom" }
androidxUiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeBom" }
androidxUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeBom" }
androidxUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeBom" }
androidxUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeBom" }
androidxMaterial3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeBom" }

hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

firebaseAuthKtx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebaseCommonKtx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

transitiveLib = { module = "com.example.transitive:transitive-lib", version.ref = "transitiveLib" }
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseFirestoreKtx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

[libraries.library]
module = "com.example.library:library"
version = "1.0.0"

[libraries.anotherLibrary]
module = "com.example.another:another-library"
version = "1.0.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase = { id = "com.google.firebase.crashlytics", version.ref = "firebasePlugin" }

